apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: api-healthcheck-policy
  namespace: synergychat
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_SERVING_PORT
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: api-service
